version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "<TASK_DEFINITION>"
        LoadBalancerInfo:
          ContainerName: "web"
          ContainerPort: "80"
Hooks:
  AfterInstall:
    - Location: scripts/migrate.sh
      Timeout: 1200
      Runas: root