version: '2'
services:
  app:
    build: .
    volumes:
      - .:/usr/local/src/sample_fargate_rails
    environment:
      REDIS_URL: redis://redis:6379/
    tty: true
    stdin_open: true
    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0'
    ports:
      - "3100:3000"
#    command: sh -c 'rm -f tmp/pids/server.pid && bundle exec rails s -p 80 -b 0.0.0.0 -e production'
#    ports:
#     - "80:80"
    depends_on:
      - app_db
  worker:
    build: .
    volumes:
      - .:/usr/local/src/sample_fargate_rails
    environment:
      REDIS_URL: redis://redis:6379/
    command: bundle exec sidekiq
    depends_on:
      - redis
  redis:
    image: redis:5.0.3-alpine
  app_db:
    image: mysql:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci