version: 2
jobs:
  build:
    docker:
      - image: circleci/python
    branches:
      only:
        - master
    steps:
      - checkout
      - run: sudo pip install awscli
      - run:
          name: Push to CodeCommit
          command: |
            export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
            export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
            git config credential.helper '!aws codecommit credential-helper $@'
            git config credential.useHttpPath true
            git push https://git-codecommit.${AWS_DEFAULT_REGION}.amazonaws.com/v1/repos/${AWS_CODE_COMMIT_REPO_NAME} master